services:
  db:
    container_name: postgres_blog
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin_blog
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: username@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "2640:80"